name: Deploy to Ubuntu server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Generate version.txt with timestamp
        run: echo "v$(date +'%Y%m%d%H%M%S')" > version.txt

      - name: Deploy to server via SSH and SCP
        run: |
          scp -o StrictHostKeyChecking=no version.txt hostapp@172.184.216.215:/var/www/html/my-html-project/
          ssh -o StrictHostKeyChecking=no hostapp@172.184.216.215 << 'EOF'
            rm -rf /var/www/html/my-html-project
            git clone https://github.com/Rajapaksha99/my-html-project.git /var/www/html/my-html-project
            sudo systemctl reload nginx
          EOF
